### ISSUE TITLE
NullPointerException in OverlayScrollPaneHack.class

### ISSUE THREAD

**Issue by nhacken** [cbfiddle/Issues#4]
Loading the application with VAqua LookAndFeel sometimes results in a NullPointerException in OverlayScrollPaneHack.class.

Unfortunately the bug cannot be reproduced and it appears only time by time but absolutely independent on code changes (no code changes made between launches with or without exception thrown, it took me at least 20 launches to get it again).

Exception in thread "main" java.lang.NullPointerException
	at org.violetlib.aqua.OverlayScrollPaneHack.reconfigure(Unknown Source)
	at org.violetlib.aqua.AquaScrollPaneUI$AquaOverlayJScrollPaneController.reconfigure(Unknown Source)
	at org.violetlib.aqua.AquaOverlayScrollPaneController.initialize(Unknown Source)
	at org.violetlib.aqua.AquaOverlayScrollPaneController.setVerticalScrollBar(Unknown Source)
	at org.violetlib.aqua.AquaScrollPaneUI$AquaOverlayJScrollPaneController.<init>(Unknown Source)
	at org.violetlib.aqua.AquaScrollPaneUI.setScrollBarStyle(Unknown Source)
	at org.violetlib.aqua.AquaScrollPaneUI.installUI(Unknown Source)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JScrollPane.setUI(JScrollPane.java:380)
	at javax.swing.JScrollPane.updateUI(JScrollPane.java:393)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:305)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:323)
	at com.reseda.dpm.gui.DPM_UI.init_gui(DPM_UI.java:104)
 -- > This is my code where I call new ScrollPane(instance of JTree);

**Comment by cbfiddle** [comment]
Does this problem happen if you create your scroll pane on the AWT event thread?

**Comment by nhacken** [comment]
When Launching my UserInterface from the AWT Thread I never got this exception again. Cannot be certain , but it seems this was the cause for the Exception.
