### ISSUE TITLE
UnsatisfiedLinkError if I try to install a default menu bar

### ISSUE THREAD

**Issue by hakanai** [cbfiddle/Issues#7]
We try to make our application look slightly more native by setting a default menu bar to the screen.

But if I try to do this with VAqua installed, I get an `UnsatisfiedLinkError`.

```
java.lang.UnsatisfiedLinkError: com.apple.laf.ScreenMenu.addMenuListeners(Lcom/apple/laf/ScreenMenu;J)J
	at com.apple.laf.ScreenMenu.addMenuListeners(Native Method)
	at com.apple.laf.ScreenMenu.addNotify(ScreenMenu.java:254)
	at java.awt.Menu.addNotify(Menu.java:183)
	at com.apple.laf.ScreenMenu.addNotify(ScreenMenu.java:234)
	at com.apple.laf.ScreenMenuBar.add(ScreenMenuBar.java:285)
	at com.apple.laf.ScreenMenuBar.addSubmenu(ScreenMenuBar.java:223)
	at com.apple.laf.ScreenMenuBar.addNotify(ScreenMenuBar.java:66)
	at com.apple.eawt._AppMenuBarHandler.installDefaultMenuBar(_AppMenuBarHandler.java:116)
	at com.apple.eawt._AppMenuBarHandler.setDefaultMenuBar(_AppMenuBarHandler.java:71)
	at com.apple.eawt.Application.setDefaultMenuBar(Application.java:384)
	at ...application code...
```

**Comment by cbfiddle** [comment]
The way that the screen menu bar is implemented in the JDK requires that Aqua LAF be loaded.

**Comment by hakanai** [comment]
Ah, that's... something I had no idea about. I thought I had seen it working with one of the other L&Fs, but I can't remember how long ago it was, so it may have changed since.

Rats, so that blocks using VAqua entirely unless I can dodge it somehow... like convincing Aqua to load whatever it needs to load first, and then loading VAqua maybe.

**Comment by cbfiddle** [comment]
I’m not having any problem with the system menu bar and I’m not aware of doing anything explicit to load Aqua.

Are you doing something to prevent Aqua from loading?

**Comment by hakanai** [comment]
Nothing that I'm aware of, other than setting VAqua as the LAF instead of Aqua. I'll have to try reducing what we're doing to a smaller program to get an idea of what is breaking. The only slightly different thing is that we're using Gum to make the actual calls to Application, but it's just a thin layer which calls straight through to Apple's API.

**Comment by cbfiddle** [comment]
It looks like the problem is failure to load a native library:

java.lang.UnsatisfiedLinkError: com.apple.laf.ScreenMenu.addMenuListeners(Lcom/apple/laf/ScreenMenu;J)J
	at com.apple.laf.ScreenMenu.addMenuListeners(Native Method)
	at com.apple.laf.ScreenMenu.addNotify(ScreenMenu.java:254)
	at java.awt.Menu.addNotify(Menu.java:183)
	at com.apple.laf.ScreenMenu.addNotify(ScreenMenu.java:234)
	at com.apple.laf.ScreenMenuBar.add(ScreenMenuBar.java:285)
	at com.apple.laf.ScreenMenuBar.addSubmenu(ScreenMenuBar.java:223)
	at com.apple.laf.ScreenMenuBar.addNotify(ScreenMenuBar.java:66)
	at com.apple.eawt._AppMenuBarHandler.installDefaultMenuBar(_AppMenuBarHandler.java:116)
	at com.apple.eawt._AppMenuBarHandler.setDefaultMenuBar(_AppMenuBarHandler.java:71)
	at com.apple.eawt.Application.setDefaultMenuBar(Application.java:384)
	at ...application code...

**Comment by hakanai** [comment]
Indeed, it looks like Apple's AquaLookAndFeel is loading some native library which VAqua's replacement AquaLookAndFeel is not loading.

So the workaround at the moment is I subclass it to override the initialisation logic:

```
    @Override
    public void initialize()
    {
        super.initialize();

        AccessController.doPrivileged((PrivilegedAction<Void>) () -> {
            System.loadLibrary("osxui");
            return null;
        });
    }
```

**Edit:** Nope, spoke too soon. It loads the library fine but fails in the same way. There must be another native library buried in another class in the same area.

**Comment by cbfiddle** [comment]
This is what I am doing that has the equivalent effect:

UIManager.getLookAndFeel()

**Comment by hakanai** [comment]
Yep, so I guess this works - programmatically load Aqua and then immediately switch it out for VAqua.

**Comment by cbfiddle** [comment]
This is actually a bug that was fixed in JDK 9.

See JDK-8166683 <https://bugs.openjdk.java.net/browse/JDK-8166683>.

I should find a way for VAqua to work around this problem in JDK 8.

**Comment by hakanai** [comment]
Interesting, we're only jumping to VAqua because we want to move to JDK 9 later, which makes this incompatibility not an issue for us anyway. It just means that we have to do the switch to VAqua only on our JDK 9 branch.
